### ISSUE TITLE
Privacy policy

### ISSUE THREAD

**Issue by 5xxx** [NickHeiner/decomissioned-fitbit-export#21]
The following blurb is mentioned on the App Authorization page.

_**Data shared with Fitbit Data Export will be governed by Nick Heiner’s privacy policy and terms of service. You can revoke this consent at any time in your Fitbit account settings. More information about these permissions can be found here.**_

However there does not appear to be any such policy or terms of service noted on the project page at Github nor on the hosting page http://fitbit-export.azurewebsites.net. Given that Fitbit profile information, possibly including email address, Birthday etc. can also be pulled with this tool and potentially shared, it would be prudent to see what _"Nick Heiner’s privacy policy or terms of service"_ actually are.  Can it please be published in a easily visible place?"

Screen Shot Below
![image](https://user-images.githubusercontent.com/37595434/37679002-12515bca-2c56-11e8-81c5-cd66a1549e8f.png)

**Comment by NickHeiner** [comment]
>  possibly including email address, Birthday etc

Email address and birthday cannot be pulled using this tool.

It's a good point that this should have a privacy policy. I didn't make one originally, because this was just a tool for my personal use. But I'll put something up.

**Comment by NickHeiner** [comment]
I didn't interpret it as a slight at all! It's a totally fair question to ask.

Fitbit now has a [complete export](https://www.fitbit.com/settings/data/export) on their site, so I've decommissioning this project. That works out best for everyone, because now people have access to their data without needing to trust a third party like myself to have a good privacy policy. :smile:
